trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src\Nahl.AppSettingsManager.sln'

- task: VSBuild@1
  inputs:
    solution: 'src\Nahl.AppSettingsManager.sln'
    configuration: 'release'
    restoreNugetPackages: true
    createLogFile: true

- task: PublishVisualStudioExtension@3
  inputs:
    connectedServiceName: 'Visual Studio MarketPlace'
    vsixFile: 'src\Nahl.AppSettingsManager.VisualStudio\bin\Release\Nahl.AppSettingsManager.VisualStudio.vsix'
    manifestFile: 'src\publishManifest.json'
    publisherId: 'muzammilkm'
    ignoreWarnings: 'VSIXValidatorWarning01,VSIXValidatorWarning02'