# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  inputs:
    solution: 'src\Nahl.AppSettingManager.sln'
    configuration: 'release'
    restoreNugetPackages: true
    createLogFile: true

- task: PublishVisualStudioExtension@3
  inputs:
    connectedServiceName: 'Visual Studio MarketPlace'
    vsixFile: '''$(Build.SourcesDirectory)\src\Nahl.AppSettingManager.VisualStudio\bin\Release\Nahl.AppSettingManager.VisualStudio.vsix'''
    manifestFile: '''$(Build.SourcesDirectory)\src\publishManifest.json'
    publisherId: 'muzammilkm'
    ignoreWarnings: 'VSIXValidatorWarning01,VSIXValidatorWarning02'